# recipe/meta.yaml
package:
  name: quantms-utils
  version: "0.0.14"

source:
  path: ../

build:
  entry_points:
    - quantmsutilsc=quantmsutils.quantmsutilsc:main
  noarch: python
  run_exports:
    - {{ pin_subpackage('quantms-utils', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.2.0
  run:
    - python
    - click
    - sdrf-pipelines>=0.0.31
    - pyopenms
    - pandas
    - numpy
    - pyarrow
    - pip
    - pip
      - ms2rescore=3.1.3
test:
  imports:
    - quantmsutils
  commands:
    - quantmsutilsc --help
  requires:
    - pip

about:
  home: https://www.github.com/bigbio/quantms-utils
  summary: Python package with scripts and helpers for the quantms workflow
  license: MIT
  license_file: LICENSE
  dev_url: https://www.github.com/bigbio/quantms-utils

extra:
  recipe-maintainers:
    - ypriverol
