# recipe/meta.yaml
package:
  name: quantms-utils
  version: "0.0.16"

source:
  path: ../

build:
  entry_points:
    - quantmsutilsc=quantmsutils.quantmsutilsc:main
  noarch: python
  run_exports:
    - {{ pin_subpackage('quantms-utils', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - pip
    - poetry-core >=1.2.0
  run:
    - python >=3.8,<3.11
    - click
    - sdrf-pipelines>=0.0.31
    - pyopenms>=2.4.0
    - pandas
    - numpy
    - pyarrow
    - ms2rescore ==3.0.3
    - deepLC ==2.2.38
    - psm-utils ==0.8.3
    - scipy ==1.13.1
    - pygam
    - protobuf ==3.19.6
test:
  imports:
    - quantmsutils
  commands:
    - quantmsutilsc --help
  requires:
    - pip

about:
  home: https://www.github.com/bigbio/quantms-utils
  summary: Python package with scripts and helpers for the quantms workflow
  license: MIT
  license_file: LICENSE
  dev_url: https://www.github.com/bigbio/quantms-utils

extra:
  recipe-maintainers:
    - ypriverol
