# recipe/meta.yaml
package:
  name: quantms-utils
  version: "0.0.12"

source:
  path: ../

build:
  entry_points:
    - quantmsutilsc=quantmsutils.quantmsutilsc:main
  noarch: python
  run_exports:
    - {{ pin_subpackage('quantms-utils', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vvv"
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools
  run:
    - click
    - sdrf-pipelines>=0.0.31
    - pyopenms
    - ms2rescore=3.0.3
    - deeplc=2.2.38
    - ms2pip=4.0.0.dev8
    - psm-utils=0.8.2
    - deeplcretrainer
    - pydantic=1.10.14
    - pandas
    - protobuf>=3.9.2,<4  # Ensure compatibility with tensorboard
    - numpy
    - pyarrow
    - pygam
    - scipy==1.13.1
    - scikit-learn

test:
  imports:
    - quantmsutils
  commands:
    - quantmsutilsc --help
  requires:
    - pip

about:
  home: https://www.github.com/bigbio/quantms-utils
  summary: Python package with scripts and helpers for the quantms workflow
  license: MIT
  license_file: LICENSE
  dev_url: https://www.github.com/bigbio/quantms-utils

extra:
  recipe-maintainers:
    - ypriverol