name: Conda Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        channels: conda-forge,defaults,bioconda

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Install mamba
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate quantmsutils
        conda install conda-forge::mamba
      shell: bash -l {0}

    - name: Install conda-build
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate quantmsutils
        conda install -n quantmsutils conda-build anaconda-client
      shell: bash -l {0}

    - name: Activate conda environment and build package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate quantmsutils
        conda build recipe
      shell: bash -l {0}

    - name: Install the built package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate quantmsutils
        mamba install --use-local quantmsutils
      shell: bash -l {0}

    - name: Test the installed package
      run: |
        mamba activate quantmsutils
        quantmsutilsc --help
      shell: bash -l {0}