name: Conda Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent hanging

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Update to latest version

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.10
        channels: conda-forge,bioconda
        activate-environment: quantmsutils
        cache-downloads: true
        cache-environment: true
        environment-file: environment.yml
        use-mamba: true

    - name: Install build dependencies
      shell: bash -l {0}
      run: |
        conda install -q conda-forge::boa conda-build anaconda-client
        mamba install -q conda-build anaconda-client

    - name: Build package
      shell: bash -l {0}
      run: |
        conda mambabuild recipe --output-folder conda-bld

    - name: Install built package
      shell: bash -l {0}
      run: |
        mamba install -q --use-local quantms-utils

    - name: Verify package
      shell: bash -l {0}
      run: |
        conda list
        quantmsutilsc --help || true  # Prevent failure if help command doesn't exist
        quantmsutilsc --version || true