name: Conda Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Update to latest version

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        python-version: 3.11
        channels: conda-forge,bioconda,defaults

    - name: Install mamba, boa and conda-build
      run: |
        mamba install conda-forge::boa

    - name: Build package
      run: |
        conda mambabuild recipe --debug --suppress-variables --override-channels --channel conda-forge --channel bioconda

    - name: Install the built package
      run: |
        mamba install --use-local quantms-utils

    - name: Output package info
      run: |
        conda list

    - name: Test the installed package
      run: |
        # this will fail. you need to create a quantmsutil env first
        conda activate quantmsutils
        quantmsutilsc --help
        quantmsutilsc --version
