name: Conda Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Update to latest version

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        channels: conda-forge,bioconda
        cache-downloads: true
        auto-update-conda: false
        activate-environment: test
        python-version: 3.11

    - name: Setup conda-build and anaconda-client
      run: |
         mamba install -q conda-build anaconda-client conda-verify

    - name: Build package
      run: |
        conda build purge-all
        conda config --set solver libmamba
        conda config --set channel_priority strict
        conda build recipe --suppress-variables --override-channels --channel conda-forge --channel bioconda --no-anaconda-upload
        mamba install --use-local quantms-utils==0.0.14

    - name: Download test data
      run: |
        wget https://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-ci-github/quantms-utils/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML
        wget https://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-ci-github/quantms-utils/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01_comet.idXML

    - name: Test percolator ms2rescore
      run: |
        quantmsutilsc ms2rescore --psm_file TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01_comet.idXML --spectrum_path TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML --processes 2 --ms2pip_model HCD2021 --feature_generators 'ms2pip,deeplc' --id_decoy_pattern ^rev --test_fdr 0.05